### ISSUE TITLE
Update the docs for Chef 12

### ISSUE THREAD

**Issue by svanharmelen** [xanzy/xanzy.github.io#2]

**Comment by hh** [comment]
Yes please, can I give a hand?

**Comment by svanharmelen** [comment]
@hh yes, sure... Just update want you think is relevant and put it n a PR... My target is to release a new version by the end of next week, so expect some more commits coming in.

Thanks!

**Comment by svanharmelen** [comment]
@hh have a look at the latest docs... I've updated everything so it's inline with the latest v0.6.x release and added Chef 12 info where I thought it was needed.

If your up for it, it would be nice to have a peer review and (if needed) a PR with additional updates to make the docs complete and up-to-date again :wink:

Thx!

**Comment by svanharmelen** [comment]
Closing as I did not receive any new feedback and the docs should be on par for Chef 12 (more of less).
